import logging
import importlib
from types import SimpleNamespace

import pytest

import cli.checkver
from cli.util import (
    extract_filament_info,
    extract_gcode_thumbnail,
    extract_layer_count,
    json_key_value,
    normalize_gcode_lines,
    parse_http_bool,
    parse_json,
    patch_gcode_time,
    pretty_json,
    pretty_mac,
    pretty_size,
    resolve_upload_rate_mbps_with_source,
    split_chunks,
    RateLimiter,
)


def test_json_key_value_parses_number_types_and_strings():
    assert json_key_value("retries=3") == ("retries", 3)
    assert json_key_value("ratio=2.5") == ("ratio", 2.5)
    assert json_key_value("mode=fast") == ("mode", "fast")


def test_json_key_value_rejects_missing_separator():
    with pytest.raises(ValueError, match="key=value"):
        json_key_value("missing-separator")


def test_resolve_upload_rate_prefers_override_over_env_and_config(monkeypatch):
    monkeypatch.setenv("UPLOAD_RATE_MBPS", "25")
    cfg = SimpleNamespace(upload_rate_mbps=5)

    rate, source = resolve_upload_rate_mbps_with_source(config=cfg, override=50)

    assert (rate, source) == (50, "override")


def test_resolve_upload_rate_uses_env_and_logs_invalid_values(monkeypatch, caplog):
    monkeypatch.setenv("UPLOAD_RATE_MBPS", "invalid")
    cfg = SimpleNamespace(upload_rate_mbps=25)

    with caplog.at_level(logging.WARNING):
        rate, source = resolve_upload_rate_mbps_with_source(config=cfg)

    assert (rate, source) == (25, "config")
    assert "Ignoring unsupported UPLOAD_RATE_MBPS='invalid'" in caplog.text


def test_resolve_upload_rate_rejects_invalid_override():
    with pytest.raises(ValueError, match="Unsupported upload rate"):
        resolve_upload_rate_mbps_with_source(override="7")


def test_normalize_gcode_lines_removes_comments_and_blanks():
    gcode = """
    ; generated by slicer
    G28 ; home axes

      G1 X10 Y10
    ; another comment
    M104 S200
    """

    assert normalize_gcode_lines(gcode) == ["G28", "G1 X10 Y10", "M104 S200"]


def test_normalize_gcode_lines_requires_string():
    with pytest.raises(TypeError, match="string"):
        normalize_gcode_lines(None)


def test_patch_gcode_time_inserts_time_before_first_g28():
    data = (
        b"; generated by OrcaSlicer\n"
        b"; estimated printing time = 1h 2m 3s\n"
        b"G28\n"
        b"G1 X10\n"
    )

    patched = patch_gcode_time(data).decode()

    assert ";TIME:3723\nG28\n" in patched
    assert patched.index(";TIME:3723") < patched.index("G28")


def test_patch_gcode_time_keeps_existing_marker():
    data = b";TIME:12\nG28\n"

    assert patch_gcode_time(data) == data


def test_extract_layer_count_reads_header_and_falls_back_to_markers():
    header = b";LAYER_COUNT:42\n; generated by slicer\nG28\n"
    fallback = b"; generated by slicer\nG28\n;LAYER_CHANGE\nG1 X1\n;LAYER_CHANGE\n"

    assert extract_layer_count(header) == 42
    assert extract_layer_count(fallback) == 2


def test_extract_layer_count_survives_blank_lines_in_header():
    data = b"; thumbnail begin\n; thumbnail end\n\n;LAYER_COUNT:17\nG28\n"

    assert extract_layer_count(data) == 17


def test_extract_filament_info_reads_orca_slicer_footer():
    data = (
        b"G28\n"
        b"; filament_settings_id = \"Sunlu Rapid PETG\"\n"
        b"; filament_type = PETG\n"
        b"; filament_vendor = Sunlu\n"
    )

    assert extract_filament_info(data) == {"type": "PETG", "vendor": "Sunlu"}


def test_extract_gcode_thumbnail_reads_embedded_png_and_prefers_largest():
    small_png = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a5ZQAAAAASUVORK5CYII="
    large_png = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAusB9WfKJeYAAAAASUVORK5CYII="
    gcode = (
        "; thumbnail begin 32x32 10\n"
        f"; {small_png}\n"
        "; thumbnail end\n"
        "; thumbnail begin 256x256 10\n"
        f"; {large_png}\n"
        "; thumbnail end\n"
    ).encode("utf-8")

    thumbnail = extract_gcode_thumbnail(gcode)

    assert thumbnail is not None
    assert thumbnail.startswith(b"\x89PNG\r\n\x1a\n")
    assert thumbnail.endswith(b"IEND\xaeB`\x82")


def test_extract_gcode_thumbnail_returns_none_without_embedded_preview():
    assert extract_gcode_thumbnail(b"G28\nM104 S200\n") is None


def test_json_and_http_helpers():
    assert parse_json({"nested": '{"value": 1}'}) == {"nested": {"value": 1}}
    assert parse_json({"nested": '[{"value": 1}]'}) == {"nested": [{"value": 1}]}
    assert '"value": 1' in pretty_json('{"value": 1}')
    assert parse_http_bool("true") is True
    assert parse_http_bool("0") is False
    with pytest.raises(ValueError):
        parse_http_bool("maybe")


def test_display_and_chunk_helpers():
    assert pretty_mac("aabbccddeeff") == "aa:bb:cc:dd:ee:ff"
    assert pretty_size(2048) == "2.00KB"
    assert split_chunks(b"abcdef", 2) == [b"ab", b"cd", b"ef"]


def test_rate_limiter_sleeps_when_ahead(monkeypatch):
    sleeps = []
    limiter = RateLimiter(1)
    monkeypatch.setattr("cli.util.time.monotonic", lambda: limiter.start_time)
    monkeypatch.setattr("cli.util.time.sleep", lambda delay: sleeps.append(delay))

    limiter.throttle(125000)

    assert sleeps and sleeps[0] > 0


def test_checkver_import_requests_minimum_python(monkeypatch):
    calls = []
    monkeypatch.setattr("cli.util.require_python_version", lambda major, minor: calls.append((major, minor)))

    importlib.reload(cli.checkver)

    assert calls == [(3, 10)]
