EVENT_PRINT_STARTED = "print_started"
EVENT_PRINT_FINISHED = "print_finished"
EVENT_PRINT_FAILED = "print_failed"
EVENT_GCODE_UPLOADED = "gcode_uploaded"
EVENT_PRINT_PROGRESS = "print_progress"

EVENTS = (
    EVENT_PRINT_STARTED,
    EVENT_PRINT_FINISHED,
    EVENT_PRINT_FAILED,
    EVENT_GCODE_UPLOADED,
    EVENT_PRINT_PROGRESS,
)

EVENT_TITLES = {
    EVENT_PRINT_STARTED: "Print started",
    EVENT_PRINT_FINISHED: "Print finished",
    EVENT_PRINT_FAILED: "Print failed",
    EVENT_GCODE_UPLOADED: "Upload complete",
    EVENT_PRINT_PROGRESS: "Print progress",
}

EVENT_ENV_OVERRIDES = {
    EVENT_PRINT_STARTED: "APPRISE_EVENT_PRINT_STARTED",
    EVENT_PRINT_FINISHED: "APPRISE_EVENT_PRINT_FINISHED",
    EVENT_PRINT_FAILED: "APPRISE_EVENT_PRINT_FAILED",
    EVENT_GCODE_UPLOADED: "APPRISE_EVENT_GCODE_UPLOADED",
    EVENT_PRINT_PROGRESS: "APPRISE_EVENT_PRINT_PROGRESS",
}


def is_known_event(event):
    return event in EVENTS
