listener 8789
protocol mqtt
cafile   /mosquitto/certs/ca-cert.pem
certfile /mosquitto/certs/server-cert.pem
keyfile  /mosquitto/certs/server-key.pem
require_certificate false
allow_anonymous true

persistence true
persistence_location /mosquitto/data/

log_type all
log_dest stdout
log_dest file /mosquitto/log/mosquitto.log
log_timestamp true
connection_messages true
